readmypen/readmypen.WebUI/Models/ErrorViewModel.cs
namespace readmypen.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

readmypen/readmypen.WebUI/Models/PictureViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace readmypen.WebUI.Models
{
    public class PictureViewModel
    {
        public int pic_Id { get; set; }
        //public string pic_PictureName { get; set; }
        public IFormFile pic_PicturePath { get; set; }
        public int usr_Id { get; set; }

    }
}

readmypen/readmypen.WebUI/Models/RoleViewModel .cs
using System.ComponentModel.DataAnnotations;

namespace readmypen.WebUI.Models
{
    public class RoleViewModel
    {
        [Display(Name = "Role Id")]
        public int rol_Id { get; set; }


        [Display(Name = "Role Description")]
        public string rol_Description { get; set; }
    }
}

readmypen/readmypen.WebUI/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace readmypen.WebUI.Models
{
    public class UserViewModel
    {
        [Display(Name = "User Id")]
        public int usr_Id { get; set; }

        [Display(Name = "Username")]
        public string usr_Username { get; set; }

        [Display(Name = "Password")]
        public string usr_Password { get; set; }

        [Display(Name = "Role Id")]
        public int rol_Id { get; set; }

    }
}

readmypen/readmypen.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using readmypen.WebUI.Models;
using System.Diagnostics;

namespace readmypen.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View();
        }

    }
}

readmypen/readmypen.WebUI/Controllers/PicturesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using readmypen.DataAccess.Entities;
using readmypen.WebUI.Models;
using Microsoft.AspNetCore.Hosting;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using readmypen.DataAccess.Repositories;

namespace readmypen.WebUI.Controllers
{
    public class PicturesController : Controller
    {
        private readonly IHostingEnvironment _environment;
        private readonly AppDbContext _context;

        public PicturesController(IHostingEnvironment environment, AppDbContext context)
        {
            _environment = environment;
            _context = context;
        }


        [HttpPost]
        public IActionResult Upload(PictureViewModel model)
        {
            // Validate the model
            //if (!ModelState.IsValid)
            //{
            //    return BadRequest(ModelState);
            //}

            // Check if a file was uploaded
            if (model.pic_PicturePath == null || model.pic_PicturePath.Length == 0)
            {
                return BadRequest("File not found.");
            }

            // Save the file to the server
            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            var filePath = Path.Combine(uploads, model.pic_PicturePath.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                model.pic_PicturePath.CopyTo(fileStream);
            }

            // Add the file information to the database
            var picture = new tbPictures
            {
                //pic_PictureName = model.pic_PictureName,
                pic_PicturePath = "/uploads/" + model.pic_PicturePath.FileName,
                usr_Id = model.usr_Id
            };
            //////_context.tbPictures.Add(picture);
            //////await _context.SaveChangesAsync();

            //////var repository = new PicturesRepository();
            //////repository.InsertPicture(picture);

            var repository = new PicturesRepository();
            repository.InsertPicture(picture.pic_PicturePath, picture.usr_Id);


            // Return the success status
            return Ok(new { status = "success", message = "File uploaded successfully." });

            ////return RedirectToAction(nameof(Index));
        }

    }
}

readmypen/readmypen.WebUI/Controllers/accountsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using readmypen.DataAccess.Interfaces;
using readmypen.WebUI.Models;

namespace readmypen.WebUI.Controllers
{
    public class accountsController : Controller
    {
        private readonly IUsersRepository _usersRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public accountsController(IUsersRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }


        // GET: AccountsController
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Enter(string username, string password)
        {
            UserViewModel model = new UserViewModel();
            model.usr_Username = username;
            model.usr_Password = password;

            var login = _usersRepository.Login(model.usr_Username, model.usr_Password);

            if(login == null)
            {
                return Json("Error");
            }
            else
            {
                HttpContext.Session.SetString("usu_NombreUsuario", login.usr_Username);
                //HttpContext.Session.SetInt32("usu_Id", login.usr_Id);
                //HttpContext.Session.SetString("usu_NombreUsuario", model.usr_Username);
                //ViewBag.Message = HttpContext.Session.GetString("usu_NombreUsuario");

                return View("~/Views/Home/Index.cshtml");
            }

        }

        public ActionResult Signup()
        {
            return View();
        }

    }
}

readmypen/readmypen.WebUI/Views/Accounts/Login.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Login Page";
}
<div class="container-logsig">
    <form asp-action="Enter" asp-controller="Accounts" class="formulario">
        <h2>Login Form</h2>
        <div class="form-group">
            <label for="username">Username:</label>
            <input asp-for="usr_Username" type="text" class="form-control caja" id="username" placeholder="Enter username" name="username">
        </div>
        <div class="form-group">
            <label for="passward">Password:</label>
            <input asp-for="usr_Password" type="password" class="form-control caja" id="password" placeholder="Enter password" name="password">
        </div>
        <div class="checkbox">
            <label><input type="checkbox" name="remember"> Remember me</label>
        </div>
        <button type="submit" class="btn btn-default buttonito">Submit</button>
    </form>
</div>

readmypen/readmypen.WebUI/Views/Accounts/Signup.cshtml
@{
    ViewData["Title"] = "Signup Page";
}
<div class="container-logsig">
    <form class="formulario" action="/action_page.php">
        <h2>Sign Up Form</h2>
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control caja" id="name" placeholder="Enter your name" name="name">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control caja" id="email" placeholder="Enter your email" name="email">
        </div>
        <div class="form-group">
            <label for="pwd">Password:</label>
            <input type="password" class="form-control caja" id="pwd" placeholder="Enter your password" name="pwd">
        </div>
        <div class="form-group">
            <label for="pwd-confirm">Confirm Password:</label>
            <input type="password" class="form-control caja" id="pwd-confirm" placeholder="Confirm your password" name="pwd-confirm">
        </div>
        <button type="submit" class="btn btn-default buttonito">Submit</button>
    </form>
</div>

readmypen/readmypen.WebUI/Views/Home/Index.cshtml
@model PictureViewModel
@{
    ViewData["Title"] = "Home Page";
}


    <div class="row">
        <div class="col-sm-5" id="div-box-title-1">
            <h3>What are we reading?</h3>
        </div>
        <div class="col-sm-7" id="div-box-title-2">
            <h3>Your Notes</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-5" id="div-box-content-1">
            <div class="delete-box">
                <i class="fa fa-close" id="closeicon" style="font-size:48px;" onclick="closeImage()"></i>
            </div>
            <!-- SELECT PICTURE FORM -->
           @* <iframe name="picture-form" style="display:none;"></iframe>*@
            <form asp-action="Upload" asp-controller="Pictures" method="post" enctype="multipart/form-data">
                <div class="preview" id="div-image-displayer">
                    <!-- deleted position:absolute -->
                    <img id="preview-selected-image" name="preview-selected-image" />
                </div>
                <div class="row" style="margin-top: 20px;">
                    <div class="input-group col-10">
                    <label asp-for="pic_PicturePath" class="custom-file-label" for="file-upload">Choose file</label>
                    <input asp-for="pic_PicturePath" type="file" name="fileToUpload" class="custom-file-input" id="file-upload" accept="image/jpeg, image/png" onchange="previewImage(event);">
                    <span asp-validation-for="pic_PicturePath" class="text-danger"></span>
                    </div>
                    <div class="input-group-append col-2">
                        <input class="btn btn-secondary" name="submit" type="submit" id="btnUpload" value="Upload" />
                    </div>
                </div>
            </form>
        </div>
        <div class="col-7" id="div-box-content-2">
            <div id="div-text-editor">
                <textarea></textarea>
            </div>
            <div style="margin-top: 20px">
                <button class="btn btn-secondary" type="button">Generate</button>
                <button class="btn btn-secondary" type="button">Copy to Clipboard</button>
            </div>
        </div>
    </div>

readmypen/readmypen.WebUI/Views/Pictures/Upload.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

readmypen/readmypen.WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor contextAccesor
@model UserViewModel
@{ string NombreUsuario = contextAccesor.HttpContext.Session.GetString("usu_NombreUsuario");}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - readmypen.WebUI</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>  -->
    <link rel="stylesheet" type="text/css" href="~/css/styles.css">
</head>
<body>
    <header>
        
    </header>
    <div class="container-fluid">
        <div class="row" style="text-align:center">
@*            <input hidden type="text" value="" />
            <div class="col-12" id="div-title">
                @if (@ViewBag.Message == "" || @ViewBag.Message == null)
                {
                    <h1>Read My Pen - Welcome!</h1>
                }
                else
                {
                    <h1>Read My Pen - Welcome, @ViewBag.Message !!</h1>

                    <input hidden value='hola' id="path" type="text" />
                }
            </div>*@

            <div class="col-12" id="div-title">
                <h1>Read My Pen - Welcome <span>@NombreUsuario</span>!</h1>
                <input hidden value='hola' id="path" type="text" />
            </div>
        </div>

        @RenderBody()
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/js/display-image.js" type="text/javascript"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>